Make debugging index creation dramatically easier
Currently Its not obvious how index's are managed created in dynamoose
using

```
dynamoose.model(name, schema, {update: true})

```

Will *delete the indexes that are currently on a table*. Which is a HUGE NO NO in production.

Especially since they can take non trivial amounts of time to get back setup... which at best causes service degradation and at worse downtime

This new change allows you to use

```
DEBUG=dynamoose:table*  <how ever you start your server i.e. node server.js or yarn serve>
```

And see the difference in the console i.e.

```
  dynamoose:table compareIndexes +0ms
indexs for compare local: { IndexName: 'fb_id-index',
  KeySchema:
   [ { AttributeName: 'fb_id', KeyType: 'HASH' },
     { AttributeName: 'fb-id', KeyType: 'RANGE' } ],
  Projection: { ProjectionType: 'ALL' } } remote: { IndexName: 'fb_id-index',
  KeySchema: [ { AttributeName: 'fb_id', KeyType: 'HASH' } ],
  Projection: { ProjectionType: 'ALL' } }
indexs for compare local: { IndexName: 'phone_number-index',
  KeySchema:
   [ { AttributeName: 'phone_number', KeyType: 'HASH' },
     { AttributeName: 'phone_number', KeyType: 'RANGE' } ],
  Projection: { ProjectionType: 'ALL' } } remote: { IndexName: 'phone_number-index',
  KeySchema: [ { AttributeName: 'phone_number', KeyType: 'HASH' } ],
  Projection: { ProjectionType: 'ALL' } }

blah blah blah

  dynamoose:table devTickets indexes are not synchronized and update flag is set to false +1ms
```

MUUCH better way to deal with

```
Error: indexes are not synchronized and update flag is set to false
```